project:
  type: website
  output-dir: docs

website:
  title: "Peter Gao"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: courses.qmd
        text: Courses
      - file: projects.qmd
        text: Projects
  page-footer:
    left: |
      &copy; Peter, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

