project:
  type: website
  output-dir: docs

website:
  title: "Peter Gao"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:project

  sidebar:
    - id: project
      title: "project"
      contents:
        - US_States.qmd
        - Wisconsin_Districts.qmd
        - mini-project2.qmd

  page-footer:
    left: |
      &copy; Peter Gao, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source